"""Add member roles

Revision ID: 283bbeedbb9e
Revises: ba7236beaa02
Create Date: 2026-09-05 13:53:04.262152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283bbeedbb9e'
down_revision = 'ba7236beaa02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('id_document_front_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('id_document_back_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('id_document_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('id_document_back_path')
        batch_op.drop_column('id_document_front_path')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
