"""Add ID document path to members

Revision ID: d5a82fce08bf
Revises: fa362ae378fc
Create Date: 2026-09-04 20:08:22.695833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a82fce08bf'
down_revision = 'fa362ae378fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_document_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('id_document_path')

    # ### end Alembic commands ###
